### 프로젝트 등록
POST {{host}}/api/v1/enterprise/project
Content-Type: application/json
Authorization: Bearer {{authenticationKey}}

{
  "name": "테스트",
  "category": ["GAME"],
  "contents": "1234",
  "reward": 10000,
  "rewardDuration": 7,
  "status": "TEST",
  "profileImageUrl": "",
  "deadlineAt": "20210131235959"
}


### 프로젝트 리스트 조회
GET {{host}}/api/v1/enterprise/projects
Authorization: Bearer {{authenticationKey}}


### 프로젝트 상세 조회
GET {{host}}/api/v1/enterprise/project?projectId=ca419db7-cbe3-42cb-a489-56cb5749a147
Authorization: Bearer {{authenticationKey}}


### 버그 등록
POST {{host}}/api/v1/enterprise/project/bug
Content-Type: application/json
Authorization: Bearer {{authenticationKey}}

{
  "projectId": "67f6736c-ad16-4889-9b07-1d74a1c61d6a",
  "title": "버그 등록 제목 테스트",
  "contents": "버그 등록 내용 테스트",
  "type": "ETC",
  "imageUrl": ["http://placehold.it/100", "http://placehold.it/101"]
}