### 회원가입 for 개인
POST {{host}}/api/v1/join
Content-Type: application/json

{
  "id": "{{memberId}}",
  "name": "테스트",
  "password": "{{password}}",
  "gender": "F",
  "email": "hyukjae89@naver.com",
  "contact": "01012341234",
  "profileImageUrl": "",
  "birthYear": "2020",
  "accountType": "I"
}

### 로그인 for 개인
POST {{host}}/api/v1/login
Content-Type: application/json

{
  "id": "{{memberId}}",
  "password": "{{password}}"
}

> {%
  client.global.set("authenticationKey", response.body.result.accessToken);
%}

### 회원가입 for 기업
POST {{host}}/api/v1/join
Content-Type: application/json

{
  "id": "{{enterpriseId}}",
  "name": "캐시버그",
  "password": "{{password}}",
  "email": "kashbug.manager@gmail.com",
  "contact": "01012345678",
  "profileImageUrl": "http://placehold.it/100",
  "accountType": "E",
  "serial": "0123456789",
  "homepageUrl": "http://kashbug.com",
  "introduce": "회사 소개글"
}

### 로그인 for 기업
POST {{host}}/api/v1/login
Content-Type: application/json

{
  "id": "{{enterpriseId}}",
  "password": "{{password}}"
}

> {%
  client.global.set("authenticationKey", response.body.result.accessToken);
%}